### ISSUE TITLE
Flashing chunks to a partition

### ISSUE THREAD

**Issue by sndcrde** [dlenski/motoflash2sh#6]
Hi,

Has anyone actually tried flashing ROMs using a bash file create by `motoflash2sh` and did it work? Any issues?

I'm a bit concerned that in the following example it's not clear how fastboot would know to write the `chunk 1` **after** the `chunk 0` instead of overwriting it. Obviously there is the sequence number in the file name but I haven't seen anything in the fastboot docs that fastboot actually parses the name of the file and determines where the chunk should go.

```
fastboot flash system system.img_sparsechunk.0 || exit 1
fastboot flash system system.img_sparsechunk.1 || exit 1
```

Thanks

**Comment by dlenski** [comment]
> Has anyone actually tried flashing ROMs using a bash file create by motoflash2sh and did it work? 

Well, ***I*** have :grimacing:. Many times on multiple devices, with multiple ROMs.

> Any issues?

Not many, nope :grimacing:. This repo has been around for 7+ years. It has only received 3 issues before this one:

- One of those was a compliment (https://github.com/dlenski/motoflash2sh/issues/2)
- Neither of the others reported any adverse effect on a phone

> I'm a bit concerned that in the following example it's not clear how fastboot would know to write the chunk 1 after the chunk 0 instead of overwriting it. Obviously there is the sequence number in the file name but **I haven't seen anything in the fastboot docs that fastboot actually parses the name of the file and determines where the chunk should go.**

You haven't seen anything about filename parsing in the fastboot docs because fastboot doesn't do any such thing.

The within-partition position/alignment/padding of the sparse chunks is part of the _format of the sparse images_ themselves. You can use https://github.com/dlenski/PySIMG/blob/master/simg_dump.py to dump/disassemble the contents of a sparse image and see exactly how this is encoded.

**Comment by sndcrde** [comment]
Thanks for the quick response. I plan to use your project to restore a phone to stock but don't want to brick it, hence the questions.

Also, found the following, which answers my question: https://www.2net.co.uk/tutorial/android-sparse-image-format

Regards,
